import 'package:flutter/material.dart';
import 'package:shadcn_ui/shadcn_ui.dart';

class InfoButton extends ShadIconButton {
  const InfoButton({
    super.key,
    super.icon = const Icon(Icons.info),
    super.iconSize,
    super.onPressed,
    super.cursor,
    super.width,
    super.height,
    super.padding,
    super.backgroundColor,
    super.hoverBackgroundColor,
    super.foregroundColor,
    super.hoverForegroundColor,
    super.autofocus = false,
    super.focusNode,
    super.pressedBackgroundColor,
    super.pressedForegroundColor,
    super.shadows,
    super.gradient,
    super.decoration = const ShadDecoration(shape: BoxShape.circle),
    super.enabled = true,
    super.onLongPress,
    super.statesController,
    super.hoverStrategies,
    super.onHoverChange,
    super.onTapDown,
    super.onTapUp,
    super.onTapCancel,
    super.onSecondaryTapDown,
    super.onSecondaryTapUp,
    super.onSecondaryTapCancel,
    super.onLongPressStart,
    super.onLongPressCancel,
    super.onLongPressUp,
    super.onLongPressDown,
    super.onLongPressEnd,
    super.onDoubleTap,
    super.onDoubleTapDown,
    super.onDoubleTapCancel,
    super.longPressDuration,
    super.onFocusChange,
  });

  const InfoButton.outline({
    super.key,
    super.icon = const Icon(Icons.info_outline),
    super.iconSize,
    super.onPressed,
    super.cursor,
    super.width,
    super.height,
    super.padding,
    super.backgroundColor,
    super.hoverBackgroundColor,
    super.foregroundColor,
    super.hoverForegroundColor,
    super.autofocus = false,
    super.focusNode,
    super.pressedBackgroundColor,
    super.pressedForegroundColor,
    super.shadows,
    super.gradient,
    super.decoration = const ShadDecoration(shape: BoxShape.circle),
    super.enabled = true,
    super.onLongPress,
    super.statesController,
    super.hoverStrategies,
    super.onHoverChange,
    super.onTapDown,
    super.onTapUp,
    super.onTapCancel,
    super.onSecondaryTapDown,
    super.onSecondaryTapUp,
    super.onSecondaryTapCancel,
    super.onLongPressStart,
    super.onLongPressCancel,
    super.onLongPressUp,
    super.onLongPressDown,
    super.onLongPressEnd,
    super.onDoubleTap,
    super.onDoubleTapDown,
    super.onDoubleTapCancel,
    super.longPressDuration,
    super.onFocusChange,
  }) : super.outline();

  const InfoButton.ghost({
    super.key,
    super.icon = const Icon(Icons.info_outline),
    super.iconSize,
    super.onPressed,
    super.cursor,
    super.width,
    super.height,
    super.padding,
    super.backgroundColor,
    super.hoverBackgroundColor,
    super.foregroundColor,
    super.hoverForegroundColor,
    super.autofocus = false,
    super.focusNode,
    super.pressedBackgroundColor,
    super.pressedForegroundColor,
    super.shadows,
    super.gradient,
    super.decoration = const ShadDecoration(shape: BoxShape.circle),
    super.enabled = true,
    super.onLongPress,
    super.statesController,
    super.hoverStrategies,
    super.onHoverChange,
    super.onTapDown,
    super.onTapUp,
    super.onTapCancel,
    super.onSecondaryTapDown,
    super.onSecondaryTapUp,
    super.onSecondaryTapCancel,
    super.onLongPressStart,
    super.onLongPressCancel,
    super.onLongPressUp,
    super.onLongPressDown,
    super.onLongPressEnd,
    super.onDoubleTap,
    super.onDoubleTapDown,
    super.onDoubleTapCancel,
    super.longPressDuration,
    super.onFocusChange,
  }) : super.ghost();
}
